
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class FrameVolume extends javax.swing.JFrame {

    /**
     * Creates new form FrameVolume
     */
    public FrameVolume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanjangBalok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLebarBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTinggiBalok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jJariBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Masukkan Panjang: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 130, 30);

        jPanjangBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPanjangBalokActionPerformed(evt);
            }
        });
        jPanel1.add(jPanjangBalok);
        jPanjangBalok.setBounds(150, 30, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 140, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Masukkan Tinggi:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 120, 30);
        jPanel1.add(jLebarBalok);
        jLebarBalok.setBounds(150, 80, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 40, 40, 20);
        jPanel1.add(jTinggiBalok);
        jTinggiBalok.setBounds(150, 130, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Masukkan Lebar:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 80, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 90, 40, 20);

        BtnBalok.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        BtnBalok.setText("Hitung");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBalok);
        BtnBalok.setBounds(110, 200, 160, 40);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 30, 150, 20);
        jPanel2.add(jSisiKubus);
        jSisiKubus.setBounds(40, 60, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 70, 40, 20);

        btnKubus.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnKubus.setText("Volume");
        btnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnKubus);
        btnKubus.setBounds(40, 120, 130, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 30, 210, 20);
        jPanel3.add(jJariBola);
        jJariBola.setBounds(40, 60, 80, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(140, 70, 40, 20);

        btnBola.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnBola.setText("Volume");
        btnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBola);
        btnBola.setBounds(40, 120, 130, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 90, 400, 300);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 320, 50);

        setBounds(0, 0, 416, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanjangBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanjangBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanjangBalokActionPerformed

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(jPanjangBalok.getText());
        lebar = Integer.parseInt(jLebarBalok.getText());
        tinggi = Integer.parseInt(jTinggiBalok.getText());
        int hasil = panjang * lebar * tinggi;
        try
        {
            JOptionPane.showMessageDialog(null, "Volume balok adalah: " + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBalokActionPerformed

    private void btnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKubusActionPerformed
        int sisi;
        sisi = Integer.parseInt(jSisiKubus.getText());
        int hasil = sisi * sisi * sisi;
        
        try
        {
            JOptionPane.showMessageDialog(null, "Luas permukaan kubus adalah: " + hasil, "luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnKubusActionPerformed

    private void btnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolaActionPerformed
        float jari;
        jari = Integer.parseInt(jJariBola.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);
        try
        {
            JOptionPane.showMessageDialog(null, "Luas permukaan bola adalah: " + hasil1, "luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: " + e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVolume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVolume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton btnBola;
    private javax.swing.JButton btnKubus;
    private javax.swing.JTextField jJariBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLebarBalok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jPanjangBalok;
    private javax.swing.JTextField jSisiKubus;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTinggiBalok;
    // End of variables declaration//GEN-END:variables
}
